### ISSUE TITLE
L1L2 Cache Config

### ISSUE THREAD

**Issue by SarahFz89** [CMU-SAFARI/ramulator#63]
Hi all,
I tried to run a sample example with L1L2 cache config with ramulator with the available traces using this commad (./ramulator configs/DDR3-config.cfg -mode=cpu cputraces/470.lbm), However, I got the below errors:
tracenum: 1
trace_list[0]: cputraces/470.lbm
ramulator: src/Processor.cpp:406: bool ramulator::Trace::get_unfiltered_request(long &, long &, Request::Type &): Assertion `false' failed.
Aborted (core dumped)

I would appreciate it if you could help me how to solve the issue.

Thanks,
Sarah

**Comment by arthasSin** [comment]
This is because the trace file you are using has L1-filtered requests. Probably it should give a better error message. 

The trace format for unfiltered traces is slightly different. We do not provide unfiltered traces as they get quite big. You will need to generate these traces yourself. I can also recommend gem5-based simulation if you would like to run a detailed simulation.

**Comment by SarahFz89** [comment]
Thank you very much arthasSin. I tried to get gem5 from "hg clone http://repo.gem5.org/gem5-stable" provided in your website, but, the link is not working. Could you please guide me which gem5 version I should use?

**Comment by arthasSin** [comment]
Here is the current github mirror: https://github.com/gem5/gem5
